default_locale: "en"
tabs:
  overview_project: "overview project"
  new_sprint: "new sprint"
  project_backlog: "project_backlog"
  sprint_wpd: "sprint_work_performance"
sprint:
  default_days: 10
  phases: "Phases"
options_to_add_more: [1, 3, 5, 10]
fields_decimal:
  "difference": 2
  "working_day": 1
